## CircleCI Config with Docker Images
# Environment variables to be defined in the build configuration:
# AUTH0_TEST_CLIENT_ID = Client id to use in test
# AUTH0_TEST_DOMAIN = Domain to use in test

version: 2
jobs:
  build:
    machine: true
      # - image: circleci/node:8.10
      # - image: appropriate/curl
    environment:
      - WEBAPP_URL: http://localhost:3000
    
    steps:
      # Depending on the project, the sample in-test might be in a subfolder.
      - checkout

      - run:
          # This could be our own script receiving the 2 values and the fullpath
          name: Replace Auth0 test credentials
          command: |
            mv $AUTH0_CFG.example $AUTH0_CFG
            sed -i 's/{CLIENT_ID}/'$AUTH0_TEST_CLIENT_ID'/g' $AUTH0_CFG
            sed -i 's/{DOMAIN}/'$AUTH0_TEST_DOMAIN'/g' $AUTH0_CFG
          environment:
            - AUTH0_CFG: 01-Login/src/app/auth/auth0-variables.ts # Find a universal way to search for it

      # - setup_remote_docker

      - run:
          name: Run pull request
          command: |
            docker build -t sample .
            docker run --network host -d -p 3000:3000 sample
          working_directory: 01-Login

      - run:
          name: Wait for app to be available
          command: |
            sleep 10
            docker run --network host --rm appropriate/curl --retry 10 --retry-connrefused -v $WEBAPP_URL

      - run:
          name: Prepare tests
          command: git clone https://github.com/lbalmaceda/webapp-tests-scripts scripts

      - run: 
          name: Run tests
          command: |
            docker create --network host --shm-size 1G --name tester alekzonder/puppeteer:latest
            docker cp $(pwd)/test.js tester:/app/index.js
            docker start -i tester
            docker cp tester:/app/sample.png $(pwd)
          working_directory: scripts

      - store_artifacts:
          path: scripts/sample.png